name: crypto_wallet
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.2
  device_preview: ^1.1.0
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  http: ^1.1.0
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
